// Vendor the three brand fonts (Fraunces, Spectral, IBM Plex Mono) from Google
// Fonts into the package so the framework carries no render-blocking third-party
// request (see ROADMAP 2.5). Re-run this to refresh: `node scripts/fetch-fonts.mjs`.
//
// We vendor EVERY range Google ships (latin, latin-ext, greek, cyrillic, …) — no
// glyphs are dropped, so any character a course types in prose still renders in
// brand. This is not lossy "subsetting": each @font-face keeps its `unicode-range`,
// so a browser still downloads only the range(s) a page actually uses (a Norwegian
// page fetches just latin/latin-ext). The extra ranges only add committed files,
// not runtime cost. The files + generated fonts.css are committed; at build time
// Vite fingerprints the woff2 and rewrites the url()s. KaTeX fonts are already
// self-hosted via the bundled `katex/dist/katex.min.css` import.

import { mkdir, writeFile, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=Spectral:wght@300;400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap";

// A modern browser UA makes Google serve woff2 (not ttf) with subset comments.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

const outDir = fileURLToPath(new URL("../src/styles/fonts/", import.meta.url));
const cssPath = fileURLToPath(new URL("../src/styles/fonts.css", import.meta.url));

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// Each @font-face is preceded by a `/* subset */` comment. Capture both.
const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const seen = new Map(); // url -> local filename (dedupe identical downloads)
const out = [
  "/*",
  " * Self-hosted brand fonts — GENERATED by scripts/fetch-fonts.mjs, do not edit.",
  " * All Google ranges of Fraunces / Spectral / IBM Plex Mono; unicode-range gates",
  " * what each page downloads.",
  " */",
  "",
];
let kept = 0;

for (const [, subset, face] of css.matchAll(blockRe)) {
  const family = /font-family:\s*'([^']+)'/.exec(face)?.[1] ?? "font";
  const weight = (/font-weight:\s*([^;]+)/.exec(face)?.[1] ?? "400").trim();
  const url = /url\(([^)]+)\)/.exec(face)?.[1];
  if (!url) continue;

  let file = seen.get(url);
  if (!file) {
    file = `${slug(family)}-${slug(weight)}-${subset}.woff2`;
    let n = 1;
    while ([...seen.values()].includes(file)) {
      file = `${slug(family)}-${slug(weight)}-${subset}-${++n}.woff2`;
    }
    const bytes = Buffer.from(
      await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer(),
    );
    await writeFile(outDir + file, bytes);
    seen.set(url, file);
    console.log(`  ${file}  (${(bytes.length / 1024).toFixed(1)} kB)`);
  }

  out.push(face.replace(/url\([^)]+\)/, `url("./fonts/${file}")`), "");
  kept++;
}

await writeFile(cssPath, out.join("\n"));
console.log(
  `\nVendored ${seen.size} woff2 file(s), ${kept} @font-face block(s) → src/styles/fonts.css`,
);
